### ISSUE TITLE
how do we actually do this ?

### ISSUE THREAD

**Issue by ithakaa** [shepheb/athens-export#6]
not being a progrmmer, i'm struggling to understad how to use this ?

I've installed Clojure CLI tool and Java on MacOS but i'm rather stuck at exporting my index file

The example returs and error (paths corrected) 

`Namespace could not be loaded: athens.export`

**Comment by Roc-kit** [comment]
I meet the same problem

**Comment by exceptionraiser** [comment]
Just figured this out. Clone this repo, cd into the repo then run the command from the readme. You should get an output of three directories

**Comment by Roc-kit** [comment]
> Just figured this out. Clone this repo, cd into the repo then run the command from the readme. You should get an output of three directories

Thanks, I finally made it!

![image](https://user-images.githubusercontent.com/79683568/140459752-4f76e8e9-e19b-4eb0-b3b5-ee4129e5160e.png)
![新建项目 (1)](https://user-images.githubusercontent.com/79683568/140460319-41e65bf7-a14a-48a0-bdb1-64b5c7c3b05f.png)

**Comment by solarkraft** [comment]
Thank you. As someone without any experience with Clojure I understood the readme to mean the module would automatically be downloaded from some respository.

**Comment by tstapler** [comment]
I updated the readme instructions in this PR https://github.com/bshepherdson/athens-export/pull/8

Let me know if the direct download is easier than compiling the project from source code.
